---
name: 'filterablearchiveextensions'
---
#NewsGridHolder:
#  extensions:
#    - 'FilterableArchiveHolderExtension'
#  pagination_control_tab: "Root.Subpages"
#  pagination_insert_before: "Subpages"
#  managed_object_class: "NewsGridPage"
#  managed_object_date_field: "Date"
#NewsGridHolder_Controller:
#  extensions:
#    - 'FilterableArchiveHolder_ControllerExtension'
#NewsGridPage_Controller:
#  extensions:
#    - 'FilterableArchiveItemExtension'